name: project_mobile
description: "Project Mobile UD Tani Rejo."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
